[platformio]
default_envs = fysetc_e4_v3
src_dir = v3/src

[env:fysetc_e4_v3]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 115200
build_flags = -D ELEGANTOTA_USE_ASYNC_WEBSERVER=1
lib_deps =
  https://github.com/SRombauts/SimplexNoise
  https://github.com/me-no-dev/AsyncTCP
  https://github.com/me-no-dev/ESPAsyncWebServer
  https://github.com/teemuatlut/TMCStepper
  https://github.com/waspinator/AccelStepper
  https://github.com/ayushsharma82/ElegantOTA

[env:fysetc_e4_v3_ota]
extends = env:fysetc_e4_v3
upload_protocol = espota
upload_port = perlin-v3.local
upload_flags =
  --auth=12345678

[env:fysetc_e4_v2]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 115200
build_flags = -D ELEGANTOTA_USE_ASYNC_WEBSERVER=1
lib_deps =
  https://github.com/SRombauts/SimplexNoise
  https://github.com/me-no-dev/AsyncTCP
  https://github.com/me-no-dev/ESPAsyncWebServer
  https://github.com/teemuatlut/TMCStepper
  https://github.com/waspinator/AccelStepper
  https://github.com/ayushsharma82/ElegantOTA

[env:fysetc_e4_v2_ota]
extends = env:fysetc_e4_v2
upload_protocol = espota
upload_port = perlin-bench.local
upload_flags =
  --auth=12345678

[env:fysetc_e4]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
; Note: To build V1, you would need to change src_dir above to 'src'
lib_deps =
  https://github.com/SRombauts/SimplexNoise
  https://github.com/me-no-dev/AsyncTCP
  https://github.com/me-no-dev/ESPAsyncWebServer
  https://github.com/teemuatlut/TMCStepper
  https://github.com/waspinator/AccelStepper
