[platformio]
default_envs = fysetc_e4_v3

[env:fysetc_e4_v3]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 115200
build_src_filter = +<../v3/src/>
build_flags = -D ELEGANTOTA_USE_ASYNC_WEBSERVER=1
lib_deps =
  https://github.com/SRombauts/SimplexNoise
  https://github.com/me-no-dev/AsyncTCP
  https://github.com/me-no-dev/ESPAsyncWebServer
  https://github.com/teemuatlut/TMCStepper
  https://github.com/waspinator/AccelStepper
  https://github.com/ayushsharma82/ElegantOTA
  gin66/FastAccelStepper @ ^0.30.15
  https://github.com/thomasfredericks/Bounce2

[env:fysetc_e4_v3_ota]
extends = env:fysetc_e4_v3
upload_protocol = espota
upload_port = perlin-v3.local
upload_flags = --auth=12345678

[env:fysetc_e4_v4]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 115200
build_src_filter = +<../v4/src/>
build_flags = -D ELEGANTOTA_USE_ASYNC_WEBSERVER=1
lib_deps =
  https://github.com/SRombauts/SimplexNoise
  https://github.com/me-no-dev/AsyncTCP
  https://github.com/me-no-dev/ESPAsyncWebServer
  https://github.com/teemuatlut/TMCStepper
  https://github.com/waspinator/AccelStepper
  https://github.com/ayushsharma82/ElegantOTA
  gin66/FastAccelStepper @ ^0.30.15
  https://github.com/thomasfredericks/Bounce2

[env:fysetc_e4_v4_ota]
extends = env:fysetc_e4_v4
upload_protocol = espota
upload_port = perlin-v4.local
upload_flags = --auth=12345678

[env:fysetc_e4_v2]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 115200
build_src_filter = +<../v2/src/>
build_flags = -D ELEGANTOTA_USE_ASYNC_WEBSERVER=1
lib_deps =
  https://github.com/SRombauts/SimplexNoise
  https://github.com/me-no-dev/AsyncTCP
  https://github.com/me-no-dev/ESPAsyncWebServer
  https://github.com/teemuatlut/TMCStepper
  https://github.com/waspinator/AccelStepper
  https://github.com/ayushsharma82/ElegantOTA
  gin66/FastAccelStepper @ ^0.30.15
  https://github.com/thomasfredericks/Bounce2

[env:fysetc_e4_v2_ota]
extends = env:fysetc_e4_v2
upload_protocol = espota
upload_port = perlin-bench.local
upload_flags = --auth=12345678
